/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    copy: typeof import('./components/TenantsPermissions copy.vue')['default']
    DepartmentsPermissions: typeof import('./components/DepartmentsPermissions.vue')['default']
    EventsPermissions: typeof import('./components/EventsPermissions.vue')['default']
    GroupsPermissions: typeof import('./components/GroupsPermissions.vue')['default']
    GuestsPermissions: typeof import('./components/GuestsPermissions.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    OffersPermissions: typeof import('./components/OffersPermissions.vue')['default']
    PartnersPermissions: typeof import('./components/PartnersPermissions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StaffPermissions: typeof import('./components/StaffPermissions.vue')['default']
    TenantsPermissions: typeof import('./components/TenantsPermissions.vue')['default']
  }
}
